//
// Created by 13871 on 2024/10/11.
//

#ifndef WIT_TOOLKIT_RECONBINATIONEDITION_CRUSHCHECKER_H
#define WIT_TOOLKIT_RECONBINATIONEDITION_CRUSHCHECKER_H
void crushChecker(int crush);
#endif //WIT_TOOLKIT_RECONBINATIONEDITION_CRUSHCHECKER_H
