//
// Created by 13871 on 2024/10/11.
//

#ifndef WIT_TOOLKIT_RECONBINATIONEDITION_TIMEFUNCTION_H
#define WIT_TOOLKIT_RECONBINATIONEDITION_TIMEFUNCTION_H
void nowTime();
void countDown();
#endif //WIT_TOOLKIT_RECONBINATIONEDITION_TIMEFUNCTION_H
